# Generated by Django 6.0 on 2026-01-01 23:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plat',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Plat', 'verbose_name_plural': 'Plats'},
        ),
        migrations.AddField(
            model_name='plat',
            name='categorie',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('PLAT', 'Plat principal'), ('DESSERT', 'Dessert'), ('BOISSON', 'Boisson'), ('ACCOMPAGNEMENT', 'Accompagnement')], default='PLAT', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du plat', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Le plat est-il disponible à la commande ?', verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du plat (formats acceptés: JPG, PNG)', null=True, upload_to='plats/%Y/%m/', verbose_name='Image du plat'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='nom',
            field=models.CharField(help_text='Nom du plat (max 200 caractères)', max_length=200, verbose_name='Nom du plat'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix en GNF (Francs Guinéens)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix unitaire'),
        ),
        migrations.AddIndex(
            model_name='plat',
            index=models.Index(fields=['disponible', 'categorie'], name='menu_plat_disponi_1437c2_idx'),
        ),
        migrations.AddIndex(
            model_name='plat',
            index=models.Index(fields=['nom'], name='menu_plat_nom_e3daf3_idx'),
        ),
    ]
