# Generated by Django 5.1.15 on 2026-01-16 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_date_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Obligatoire pour les serveurs, cuisiniers, comptables et admins', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Adresse email'),
        ),
        migrations.AddField(
            model_name='user',
            name='nom_complet',
            field=models.CharField(blank=True, help_text='Obligatoire pour les serveurs, cuisiniers, comptables et admins', max_length=200, null=True, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, help_text='Obligatoire pour les serveurs, cuisiniers, comptables et admins', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format valide: +224XXXXXXXXX ou XXXXXXXXX (9-20 chiffres)', regex='^\\+?[0-9]{9,20}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
