# Generated by Django 6.0 on 2025-12-30 09:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_table', models.CharField(max_length=10, unique=True, verbose_name='Numéro de table')),
                ('nombre_places', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de places')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'RTABLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='table_restaurant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['numero_table'],
            },
        ),
    ]
