# Generated by Django 5.1.15 on 2026-01-19 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name="Token d'authentification")),
                ('password_hash', models.CharField(max_length=128, verbose_name='Hash du mot de passe')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('table', models.OneToOneField(limit_choices_to={'role': 'Rtable'}, on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='Table associée')),
            ],
            options={
                'verbose_name': 'Token de table',
                'verbose_name_plural': 'Tokens de tables',
            },
        ),
    ]
