# Generated by Django 5.1.15 on 2026-01-30 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_tabletoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerestaurant',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'role': 'Rtable'}, on_delete=django.db.models.deletion.CASCADE, related_name='table_restaurant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
    ]
