# Generated by Django 5.1.15 on 2026-01-30 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_commande_date_paiement'),
        ('restaurant', '0003_alter_tablerestaurant_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='Token de session')),
                ('django_session_key', models.CharField(max_length=40, unique=True, verbose_name='Clé de session Django')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date du paiement')),
                ('est_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('commande_payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_associee', to='commandes.commande', verbose_name='Commande payée')),
                ('table', models.ForeignKey(limit_choices_to={'role': 'Rtable'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Session de table',
                'verbose_name_plural': 'Sessions de tables',
                'ordering': ['-date_creation'],
            },
        ),
    ]
