# Generated by Django 6.0 on 2025-12-30 09:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant total')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SERVIE', 'Servie'), ('PAYEE', 'Payée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_commande', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('serveur_ayant_servi', models.ForeignKey(blank=True, limit_choices_to={'role': 'RSERVEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_servies', to=settings.AUTH_USER_MODEL, verbose_name='Serveur')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='restaurant.tablerestaurant', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande', verbose_name='Commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='menu.plat', verbose_name='Plat')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'unique_together': {('commande', 'plat')},
            },
        ),
    ]
