# Generated by Django 6.0 on 2026-01-09 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_remove_commande_serveur_ayant_servi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='serveur_ayant_servi',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Rserveur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_servies', to=settings.AUTH_USER_MODEL, verbose_name='Serveur ayant servi'),
        ),
    ]
