# Generated by Django 5.1.15 on 2026-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_serveur_ayant_servi'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
    ]
